server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /saas {
        return 308 /saas/;
    }

    location /saas/ {
        try_files $uri $uri/ /saas/index.html;
    }
}
